name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Configuración adicional para Pull Requests
          SONAR_PULL_REQUEST_BASE: ${{ github.base_ref }}
          SONAR_PULL_REQUEST_BRANCH: ${{ github.head_ref }}
          SONAR_PULL_REQUEST_KEY: ${{ github.event.pull_request.number }}

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}